apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project
  labels:
    app: flaskapp
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: danyyanez/sba_kuber
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80